### ISSUE TITLE
App fails to run with thread 'main' panicked

### ISSUE THREAD

**Issue by jwestall** [jwestall/cosmic-weather#2]
Latest changes have resulted in builds passing but unable to run the app. Full stack trace below.

```
thread 'main' panicked at src/app.rs:99:33:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:144:5
   3: core::option::Option<T>::unwrap
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/option.rs:931:21
   4: cosmic_weather::app::NavPage::title
             at ./src/app.rs:99:33
   5: <cosmic_weather::app::App as cosmic::app::Application>::init
             at ./src/app.rs:148:23
   6: <cosmic::app::cosmic::Cosmic<T> as iced::wayland::Application>::new
             at /home/jacob/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0caff62/src/app/cosmic.rs:108:32
   7: <iced::wayland::Instance<A> as iced_sctk::application::Application>::new
             at /home/jacob/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0caff62/iced/src/wayland/mod.rs:167:30
   8: iced_sctk::application::run::{{closure}}
             at /home/jacob/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0caff62/iced/sctk/src/application.rs:238:26
   9: <cosmic::executor::single::Executor as iced_futures::executor::Executor>::enter
             at /home/jacob/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0caff62/src/executor/single.rs:31:9
  10: iced_futures::runtime::Runtime<Executor,Sender,Message>::enter
             at /home/jacob/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0caff62/iced/futures/src/runtime.rs:51:9
  11: iced_sctk::application::run
             at /home/jacob/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0caff62/iced/sctk/src/application.rs:238:9
  12: iced::wayland::Application::run
             at /home/jacob/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0caff62/iced/src/wayland/mod.rs:130:12
  13: cosmic::app::run
             at /home/jacob/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/0caff62/src/app/mod.rs:155:5
  14: cosmic_weather::main
             at ./src/main.rs:42:5
  15: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by jwestall** [comment]
Fixed as of commit eacea48.
